services:
  server:
    image: ghcr.io/arckoor/flare-server:latest
    build: server
    container_name: flare-server
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./config.toml:/app/config.toml
      - flare-data:/app/storage
    networks:
      - flare-network
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
  frontend:
    image: ghcr.io/arckoor/flare-frontend:latest
    build: frontend
    container_name: flare-frontend
    restart: unless-stopped
    depends_on:
      - server
  postgres:
    image: postgres:18
    container_name: flare-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: flare
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: flare-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - flare-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  valkey:
    image: valkey/valkey:8
    container_name: flare-valkey
    restart: unless-stopped
    networks:
      - flare-network
    volumes:
      - valkey-data:/data
    healthcheck:
      test: valkey-cli ping | grep PONG
      interval: 10s
      timeout: 5s
      retries: 5
    command: valkey-server --appendonly yes


networks:
  flare-network:
    internal: true

volumes:
  postgres-data:
  valkey-data:
  flare-data:
