//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ephemeral_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub cookie: String,
    pub ip: String,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
    #[sea_orm(column_type = "Double")]
    pub last_seen_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ephemeral_user_vote::Entity")]
    EphemeralUserVote,
}

impl Related<super::ephemeral_user_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EphemeralUserVote.def()
    }
}

impl Related<super::vote::Entity> for Entity {
    fn to() -> RelationDef {
        super::ephemeral_user_vote::Relation::Vote.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::ephemeral_user_vote::Relation::EphemeralUser
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
