//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ephemeral_user_vote")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub vote_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ephemeral_user_id: i32,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ephemeral_user::Entity",
        from = "Column::EphemeralUserId",
        to = "super::ephemeral_user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    EphemeralUser,
    #[sea_orm(
        belongs_to = "super::vote::Entity",
        from = "Column::VoteId",
        to = "super::vote::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vote,
}

impl Related<super::ephemeral_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EphemeralUser.def()
    }
}

impl Related<super::vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vote.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
