//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "scheduled_image")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub scheduled_poll_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: String,
    #[sea_orm(column_type = "Double")]
    pub next_occurrence: f64,
    pub approved: bool,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::image::Entity",
        from = "Column::ImageId",
        to = "super::image::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Image,
    #[sea_orm(
        belongs_to = "super::scheduled_poll::Entity",
        from = "Column::ScheduledPollId",
        to = "super::scheduled_poll::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ScheduledPoll,
}

impl Related<super::image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Image.def()
    }
}

impl Related<super::scheduled_poll::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledPoll.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
