//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::api_params::RecurrenceRule;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "scheduled_poll")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(column_type = "Double")]
    pub next_occurrence: f64,
    #[sea_orm(column_type = "Double")]
    pub cutoff: f64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub recurrence_rule: Option<RecurrenceRule>,
    pub submission_limit: Option<i32>,
    pub needs_approval: bool,
    pub reject_duplicates: bool,
    pub title_template: String,
    #[sea_orm(column_type = "Text")]
    pub info: String,
    pub voting_limit: i32,
    #[sea_orm(column_type = "Double")]
    pub voting_duration: f64,
    pub group_id: Option<String>,
    pub owner_id: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
    #[sea_orm(column_type = "Double")]
    pub updated_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::group::Entity",
        from = "Column::GroupId",
        to = "super::group::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Group,
    #[sea_orm(has_many = "super::poll::Entity")]
    Poll,
    #[sea_orm(has_many = "super::scheduled_image::Entity")]
    ScheduledImage,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::OwnerId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    User,
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Group.def()
    }
}

impl Related<super::poll::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Poll.def()
    }
}

impl Related<super::scheduled_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledImage.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::image::Entity> for Entity {
    fn to() -> RelationDef {
        super::scheduled_image::Relation::Image.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::scheduled_image::Relation::ScheduledPoll.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
