//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    Serialize,
    Deserialize,
    Hash,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "oauth_provider")]
#[serde(rename_all = "snake_case")]
pub enum OauthProvider {
    #[sea_orm(string_value = "discord")]
    Discord,
    #[sea_orm(string_value = "github")]
    Github,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    Serialize,
    Deserialize,
    Hash,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "permissions")]
#[serde(rename_all = "snake_case")]
pub enum Permissions {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "manage_groups")]
    ManageGroups,
    #[sea_orm(string_value = "manage_polls")]
    ManagePolls,
    #[sea_orm(string_value = "manage_scheduled_polls")]
    ManageScheduledPolls,
    #[sea_orm(string_value = "approve_scheduled_poll_submissions")]
    ApproveScheduledPollSubmissions,
}
