//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use super::sea_orm_active_enums::Permissions;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub permissions: Vec<Permissions>,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
    #[sea_orm(column_type = "Double")]
    pub updated_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::group::Entity")]
    Group,
    #[sea_orm(has_many = "super::group_join_request::Entity")]
    GroupJoinRequest,
    #[sea_orm(has_many = "super::group_user::Entity")]
    GroupUser,
    #[sea_orm(has_many = "super::image::Entity")]
    Image,
    #[sea_orm(has_many = "super::o_auth_user::Entity")]
    OAuthUser,
    #[sea_orm(has_many = "super::poll::Entity")]
    Poll,
    #[sea_orm(has_many = "super::scheduled_poll::Entity")]
    ScheduledPoll,
}

impl Related<super::group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Group.def()
    }
}

impl Related<super::group_join_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupJoinRequest.def()
    }
}

impl Related<super::group_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupUser.def()
    }
}

impl Related<super::image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Image.def()
    }
}

impl Related<super::o_auth_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OAuthUser.def()
    }
}

impl Related<super::poll::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Poll.def()
    }
}

impl Related<super::scheduled_poll::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledPoll.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
