//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vote")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub image_id: String,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ephemeral_user_vote::Entity")]
    EphemeralUserVote,
    #[sea_orm(
        belongs_to = "super::image::Entity",
        from = "Column::ImageId",
        to = "super::image::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Image,
}

impl Related<super::ephemeral_user_vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EphemeralUserVote.def()
    }
}

impl Related<super::image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Image.def()
    }
}

impl Related<super::ephemeral_user::Entity> for Entity {
    fn to() -> RelationDef {
        super::ephemeral_user_vote::Relation::EphemeralUser.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::ephemeral_user_vote::Relation::Vote.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
