FROM rust:latest AS builder

WORKDIR /app

COPY . .

RUN cargo build --bin flare --release

FROM debian:bookworm-slim

RUN apt-get update

WORKDIR /app

COPY --from=builder /app/target/release/flare /app/flare

CMD [ "/app/flare" ]
