[package]
name = "flare"
version = "0.1.1"
edition = "2024"
default-run = "flare"

[lib]
doctest = false

[[bin]]
name = "flare"
path = "src/bin/main.rs"
test = false

[[bin]]
name = "api-doc"
path = "src/bin/openapi.rs"
test = false

[[bin]]
name = "fuzz"
path = "src/bin/fuzz.rs"
test = false

[dependencies]
ammonia = "4.1.2"
axum = { version = "0.8.7", features = ["multipart"] }
axum-extra = { version = "0.12.2", features = [
  "cookie",
  "typed-header",
  "with-rejection",
] }
axum-server = { version = "0.7.3", features = ["tls-rustls"] }
botan = { git = "https://github.com/arckoor/botan-rs", branch = "ffi-with-release" }
chrono = "0.4.42"
config = { version = "0.15.19", features = ["toml"], default-features = false }
cookie = "0.18.1"
cuid2 = "0.1.4"
hyper = "1.8.1"
image = { version = "0.25.9", features = [
  "jpeg",
  "png",
], default-features = false }
jsonwebtoken = { git = "https://github.com/arckoor/jsonwebtoken", branch = "custom-provider", features = [
  "custom-provider",
] }
mime = "0.3.17"
oauth2 = "5.0.0"
rand = "0.9.2"
redis = { version = "0.32.7", features = ["aio", "tokio-comp"] }
reqwest = { version = "0.12.24", features = [
  "rustls-tls",
  "json",
], default-features = false }
rustls = { version = "0.23.35", features = [
  "aws_lc_rs",
], default-features = false }
sea-entity = { path = "../sea-entity" }
sea-migration = { path = "../sea-migration" }
sea-orm = { version = "1.1.19", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
secstr = "0.5.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_with = "3.16.0"
tempfile = { version = "3.23.0" }
tokio = { version = "1.48.0", features = ["full"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.7", features = ["fs", "trace"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20" }
utoipa = { version = "5.4.0" }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum", "vendored"] }

[features]
default = []
sim = []
fuzz = ["sim"]
