[package]
name = "flare"
version = "0.1.1"
edition = "2024"
default-run = "flare"

[lib]
doctest = false

[[bin]]
name = "flare"
path = "src/bin/main.rs"
test = false

[[bin]]
name = "api-doc"
path = "src/bin/openapi.rs"
test = false

[dependencies]
ammonia = "4.1.0"
axum = { version = "0.8.4", features = ["multipart"] }
axum-extra = { version = "0.10.1", features = ["cookie", "typed-header"] }
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
botan = { version = "0.11.1", features = ["vendored"] }
config = { version = "0.15.11", features = ["toml"], default-features = false }
cookie = "0.18.1"
cuid2 = "0.1.4"
hyper = "1.6.0"
image = { version = "0.25.6", features = [
  "jpeg",
  "png",
], default-features = false }
jsonwebtoken = { version = "9.3.1" }
mime = "0.3.17"
oauth2 = "5.0.0"
rand = "0.9.1"
redis = { version = "0.31.0", features = ["aio", "tokio-comp"] }
reqwest = { version = "0.12.19", features = [
  "rustls-tls",
  "json",
], default-features = false }
rustls = { version = "0.23.27", features = [
  "aws_lc_rs",
], default-features = false }
sea-entity = { path = "../sea-entity" }
sea-migration = { path = "../sea-migration" }
sea-orm = { version = "1.1.12", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
secstr = "0.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.6", features = ["fs", "trace"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
utoipa = { version = "5.3.1" }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }

[features]
default = []
sim = []
fuzz = ["sim"]
