name: ci

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: server

concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        command: ["fmt -- --check", "clippy -- -D warnings"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo ${{ matrix.command }}
        shell: "nix develop -c bash -e {0}"

  build:
    strategy:
      fail-fast: false
      matrix:
        build-flags: ["", "--release"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: db-start && ctest ${{ matrix.build-flags }}
        shell: "nix develop -c bash -e {0}"

  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: arckoor-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build
      - run: docker image load < result

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: db-start && cov-ci
        shell: "nix develop -c bash -e {0}"
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: db-start && fuzz
        shell: "nix develop -c bash -e {0}"
      - name: Upload logs
        if: "!cancelled()"
        uses: actions/upload-artifact@v4
        with:
          name: fuzz.log
          path: server/fuzz.log
